name: news
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http:
  mobx:
  flutter_mobx:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:
  faker:
  build_runner:
  mobx_codegen:

flutter:
  uses-material-design: true
